### PR TITLE
fix: add support for binary files

### PR DESCRIPTION
**Pull request by marcus-bcl**
This pull requests adds support for files that are not UTF8-encoded - for example JAR files.  Previously these would be corrupted on upload.

Inspiration taken from https://github.com/google/go-github/issues/1293 and https://github.com/maticzav/github-tree.

### CODE REVIEW

**Comment by dsanders11** [comment]
Hi @marcus-bcl, thanks for the PR!

I'll try to give this a more thorough review later in the week, but I have some initial questions after a quick glance.
* "Previously these would be corrupted on upload." - do you have an example of what the corruption looks like? It would be good to extend the integration test to confirm binary files are supported, but the test would need to verify they're not corrupted, so knowing what you were seeing would be helpful.
* Is `detect-character-encoding` necessary? Could all blobs simply be created with base64 encoding? If the encoding is just for the API call to GitHub and doesn't affect the final result, I think it would be better to avoid the usage of `detect-character-encoding`.

**Comment by dsanders11** [comment]
Realized this issue is going to bite my usage as well soon (thanks for pointing it out!), so I made some time to dig into it more. In my testing just base64-encoding all content going to `createBlob` ends up with the desired result, so `detect-character-encoding` shouldn't be necessary.

I made [a branch](https://github.com/dsanders11/github-app-commit-action/tree/fix/binary-files) with a more concise version of your changes in this PR, with an integration test that I've confirmed fails without the code change and passes with it. Could you verify it works for your use case? Should be able to use it with `dsanders11/github-app-commit-action@fix/binary-files`.

**Comment by marcus-bcl** [comment]
> Realized this issue is going to bite my usage as well soon (thanks for pointing it out!), so I made some time to dig into it more. In my testing just base64-encoding all content going to `createBlob` ends up with the desired result, so `detect-character-encoding` shouldn't be necessary.
> 
> I made [a branch](https://github.com/dsanders11/github-app-commit-action/tree/fix/binary-files?rgh-link-date=2024-08-07T02%3A38%3A57Z) with a more concise version of your changes in this PR, with an integration test that I've confirmed fails without the code change and passes with it. Could you verify it works for your use case? Should be able to use it with `dsanders11/github-app-commit-action@fix/binary-files`.

That's great, your version looks much simpler.  I'll give it a try today and let you know, thank you!

**Comment by marcus-bcl** [comment]
@dsanders11 I've tested from your branch and all looks good.

Here's an example of the JAR file that was uploaded before, which doesn't run and fails checksum validation: [gradle/wrapper/gradle-wrapper.jar](https://github.com/ministryofjustice/hmpps-probation-integration-services/pull/4128/files#diff-12277790711b9f7dc1eb1b40d025e36afe07269ea7fa5a5745dff1079facbc61)

And here's the JAR file that was uploaded using your branch, which works as expected: [gradle/wrapper/gradle-wrapper.jar](https://github.com/ministryofjustice/hmpps-probation-integration-services/pull/4142/files#diff-12277790711b9f7dc1eb1b40d025e36afe07269ea7fa5a5745dff1079facbc61)

Thanks again!

**Comment by dsanders11** [comment]
Merged that branch and it's released now as v1.4.1, thanks again!

**Pull request closed without merging**
